name: Run Tests

on:
  push:
    # Запускать при пуше в ветку master, а не main
    # Ваш код лежит в master, поэтому меняем имя ветки
    branches: [ master ] 
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Run Python Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      # Если pip не может найти пакеты, тесты падают
      run: |
        python -m pip install --upgrade pip
        # Устанавливаем зависимости
        pip install -r requirements.txt
        
    - name: Run tests
      # САМОЕ ВАЖНОЕ ИСПРАВЛЕНИЕ: 
      # Мы используем Python module mode (-m) и флаг --pyargs, 
      # чтобы pytest корректно нашел все модули и пути.
      # Кроме того, мы указываем путь к папке tests
      run: pytest -v tests/
