name: Run Tests

on:
  push:
    # ИСПРАВЛЕНО: Запускать при пуше в ветку master (поскольку вы ее используете)
    branches: [ master ] 
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Run Python Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      # Устанавливаем зависимости
      run: |
        python -m pip install --upgrade pip
        # ⚠️ ДОБАВЛЯЕМ pytest-asyncio для работы с асинхронными тестами (async def)
        pip install -r requirements.txt pytest-asyncio
        
    - name: Run tests
      # Запускаем pytest, указывая папку tests/
      run: pytest -v tests/
