name: Run Tests

# Запускаем при пуше в master и при PR в master
on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Run Python Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      # Устанавливаем зависимости из requirements.txt и добавляем плагин для асинхронных тестов
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pytest-asyncio
        
    - name: Run tests
      # Запускаем pytest. Он сам найдет тесты в папке 'tests/'
      # ⚠️ ПАЙПЛАЙН УПАДЕТ, ПОКА ВЫ НЕ ИСПРАВИТЕ ИМПОРТ 'fake_db' В ВАШИХ ФАЙЛАХ ТЕСТОВ (test_api.py)
      run: pytest -v
